project: PixelCNN
mode: train

datamodule:
  challenge: singlecoil
  data_path: D:\knee_dataset
  batch_size: 4
  kspace:
    mode: adaptive
    size_x: 640
    size_y: 320
    pooling: avg
    
  num_workers: 8
  use_dataset_cache_file: True

model:
  in_channels: 1
  n_layers: 8
  hidden_channels: 64
  lr: 0.0003 
  test_criterion:
  channel_mode: real
  ckpt_path: pixelcnn\lightning_logs\version_2\checkpoints\epoch=0-step=34742.ckpt

trainer:
  max_epochs: 10
  default_root_dir: "TryOutNewStuff"
  callbacks:
    model_ckpt:
      save_top_k: 2
      monitor: val_loss
      mode: min
  


