project: PixelCNN
mode: test

datamodule:
  challenge: singlecoil
  data_path: D:\knee_dataset
  batch_size: 1
  kspace:
    mode: center_crop
    size_x: 320
    size_y: 320
  mask_func:
    type: random_info
    center_fractions: [0.04, 0.08]
    accelerations: [8, 4]
  num_workers: 8
  use_dataset_cache_file: True

model:
  in_channels: 1
  n_layers: 8
  hidden_channels: 64
  lr: 0.0003 
  test_criterion: mse
  channel_mode: real
  ckpt_path: pixelcnn\lightning_logs\version_2\checkpoints\epoch=0-step=34742.ckpt

trainer:
  max_epochs: 10
  default_root_dir: "TryOutNewStuff"
  callbacks:
    model_ckpt:
      save_top_k: 2
      monitor: val_loss
      mode: min
  


